### ISSUE TITLE
Frends.AzureBlobStorage.UploadBlob

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.AzureBlobStorage#1]
This issue should be done using the current task as the baseline (https://github.com/CommunityHiQ/Frends.Community.Azure.Blob).

However, the following should be noted:
- The task should have its own NuGet
- Do not output source file name in result, it is redundant
- Only output the URI of uploaded blob as string
- Go through the parameters and separate them into input/options tabs, since those are all in one tab currently
- The task has to have good unit test coverage, Azure can be used for tests
- No integration tests are required besides just testing in unit tests
- Perf tests not needed since Azure and internet speed are main bottleneks
- We need to add and check SonarCube linting and go through warnings on that
- Need to setup actions workflows
- Update the readme with new task names, testing section, and such

**Comment by Svenskapojkarna** [comment]
Initial implementation of the task is done. CI also added.

**Comment by jefim** [comment]
AzureBlobStorage (Download and Upload tasks)

- Missing root README.md
- Needs CHANGELOG in separate file
- Remove .NET Standard as target framework

**Comment by Svenskapojkarna** [comment]
Made changes to make the task compliant with current guidelines.
