### ISSUE TITLE
Frends.AzureBlobStorage.ReadBlob

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.AzureBlobStorage#12]
This issue should be done using the current task as the baseline (https://github.com/CommunityHiQ/Frends.Community.Azure.Blob).

Also remember https://github.com/FrendsPlatform/FrendsTasks/wiki#task-checklist

**Comment by ttossavainen** [comment]
Done.
User can read a single file from Azure blob storage using connection string or SAS Token.
