### ISSUE TITLE
Frends.AzureBlobStorage.DeleteBlob

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.AzureBlobStorage#2]
This issue should be done using the current task as the baseline (https://github.com/CommunityHiQ/Frends.Community.Azure.Blob).

However, the following should be noted:
- The task should have its own NuGet
- The task should just return true/false
- The task has to have good unit test coverage, Azure can be used for tests
- No integration tests are required besides just testing in unit tests
- Perf tests not needed since Azure and internet speed are main bottlenecks
- We need to add and check SonarCube linting and go through warnings on that
- Need to setup actions workflows
- Update the readme with new task names, testing section, and such

**Comment by Svenskapojkarna** [comment]
Initial implementation of the task completed.
