### ISSUE TITLE
ReadBlob: Feature to use access token as authentication method

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.AzureBlobStorage#40]
Feature has been implemented to Frends.Community.Azure.Blob-paskage tasks where user is able to use access token as authentication method. In the Community side the implementation is done so that the access token is fetched from Azure AD using client credentials flow. It should be discussed if this is is a good way to go or should the task just take the access token and move responsibility of fetching the token to the user.

Example implementation: https://github.com/CommunityHiQ/Frends.Community.Azure.Blob/commit/502af2a53dc945b44cad8fbce6614dc961f0a060

**Comment by ttossavainen** [comment]
https://github.com/FrendsPlatform/Frends.AzureBlobStorage/pull/47

**Comment by ttossavainen** [comment]
merged
