### ISSUE TITLE
UploadBlob: Feature to add index tags.

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.AzureBlobStorage#45]
New feature has been implemented in Frends.Community.Azure.Blob.UploadFileAsync, where user is able to add index tags to the blob which is uploaded. The same feature should be implemented also to this task.

### Implementation proposal
https://github.com/CommunityHiQ/Frends.Community.Azure.Blob/pull/29

**Comment by ttossavainen** [comment]
merged
