### ISSUE TITLE
Download - check that we handle file names properly, if they contain non permitted file system symbols

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.AzureBlobStorage#49]
Based on this ticket: https://github.com/CommunityHiQ/Frends.Community.Azure.Blob/issues/27

**Comment by Svenskapojkarna** [comment]
https://github.com/CommunityHiQ/Frends.Community.Azure.Blob/issues/27

**Comment by ttossavainen** [comment]
merged
